"use client";

import { useEffect, useState } from "react";
import { AlertTriangle, ArrowDownRight, ArrowUpRight, Boxes, CircleDollarSign } from "lucide-react";
import { api, formatDate, formatMoney } from "@/lib/api";
import type { InventoryData } from "@/lib/types";
import { Empty, ErrorNotice, PageTitle, Panel, Spinner, StatusPill } from "@/components/ui";

export default function InventoryView() {
  const [data, setData] = useState<InventoryData | null>(null); const [error, setError] = useState("");
  useEffect(() => { api.get<InventoryData>("/inventory").then(setData).catch((e) => setError(e.message)); }, []);
  if (!data && !error) return <Spinner label="Loading inventory" />; if (!data) return <ErrorNotice message={error} />;
  const units = data.products.reduce((sum, p) => sum + p.stock, 0); const value = data.products.reduce((sum, p) => sum + p.stock * Number(p.costPrice), 0);
  return <div><PageTitle title="Inventory" subtitle="Live stock position and movement history" action={<a href="/purchases" className="inline-flex min-h-10 items-center rounded-xl bg-indigo-600 px-4 text-sm font-semibold text-white">Receive stock</a>} />
    <div className="mb-4 grid gap-3 sm:grid-cols-3"><Panel className="p-4"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-indigo-50 text-indigo-600"><Boxes /></span><div><p className="text-xs text-slate-500">Total stock units</p><b className="text-xl">{units.toLocaleString()}</b></div></div></Panel><Panel className="p-4"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-emerald-50 text-emerald-600"><CircleDollarSign /></span><div><p className="text-xs text-slate-500">Stock cost value</p><b className="text-xl">{formatMoney(value)}</b></div></div></Panel><Panel className="p-4"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-amber-50 text-amber-600"><AlertTriangle /></span><div><p className="text-xs text-slate-500">Low-stock products</p><b className="text-xl">{data.lowStock.length}</b></div></div></Panel></div>
    <div className="grid gap-4 xl:grid-cols-[.8fr_1.2fr]"><Panel><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-bold">Low-stock alerts</h2><p className="text-xs text-slate-500">At or below reorder level</p></div>{data.lowStock.length ? <div className="divide-y divide-slate-100">{data.lowStock.map((p) => <div key={p.id} className="flex items-center gap-3 px-5 py-3.5"><span className="grid h-10 w-10 place-items-center rounded-xl bg-amber-50 text-amber-600"><AlertTriangle size={18} /></span><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{p.name}</p><p className="text-xs text-slate-400">Alert at {p.lowStock} {p.unit}</p></div><b className="text-sm text-amber-600">{p.stock} left</b></div>)}</div> : <Empty title="Healthy stock" text="Nothing needs reordering right now." />}</Panel>
      <Panel className="overflow-hidden"><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-bold">Stock movements</h2><p className="text-xs text-slate-500">Latest sales, purchases and adjustments</p></div>{data.movements.length ? <div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="px-5 py-3">Product</th><th className="px-4 py-3">Type</th><th className="px-4 py-3">Quantity</th><th className="px-4 py-3">Reference</th><th className="px-4 py-3">Date</th></tr></thead><tbody className="divide-y divide-slate-100">{data.movements.map((m) => <tr key={m.id}><td className="px-5 py-3"><b>{m.product.name}</b><p className="text-xs text-slate-400">{m.product.sku}</p></td><td className="px-4 py-3"><StatusPill value={m.type} /></td><td className={`px-4 py-3 font-bold ${m.quantity >= 0 ? "text-emerald-600" : "text-rose-600"}`}><span className="inline-flex items-center gap-1">{m.quantity >= 0 ? <ArrowUpRight size={15} /> : <ArrowDownRight size={15} />}{m.quantity > 0 ? "+" : ""}{m.quantity}</span></td><td className="px-4 py-3 text-xs text-slate-500">{m.reference || "—"}</td><td className="px-4 py-3 text-xs text-slate-500">{formatDate(m.createdAt, true)}</td></tr>)}</tbody></table></div> : <Empty title="No stock history" text="Inventory movements will appear here." />}</Panel></div>
  </div>;
}
