"use client";

import { useEffect, useState } from "react";
import { Plus, Save, ShieldCheck, UserCog } from "lucide-react";
import { api, formatDate } from "@/lib/api";
import type { Role, User } from "@/lib/types";
import { Button, Empty, ErrorNotice, Field, Input, Modal, PageTitle, Panel, Select, Spinner, Textarea } from "@/components/ui";

const defaults = { shopName: "", shopAddress: "", shopPhone: "", currency: "৳", taxRate: "0", receiptFooter: "" };
export default function SettingsView({ mode }: { mode: "settings" | "users" }) {
  const [settings, setSettings] = useState(defaults); const [users, setUsers] = useState<User[]>([]); const [form, setForm] = useState<{ name: string; email: string; password: string; role: Role }>({ name: "", email: "", password: "", role: "CASHIER" }); const [open, setOpen] = useState(false); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [saved, setSaved] = useState(false); const [error, setError] = useState("");
  const load = async () => { setLoading(true); setError(""); try { if (mode === "settings") { const data = await api.get<{ settings: Record<string, string> }>("/settings"); setSettings({ ...defaults, ...data.settings }); } else setUsers((await api.get<{ users: User[] }>("/users")).users); } catch (e) { setError(e instanceof Error ? e.message : "Could not load data"); } finally { setLoading(false); } };
  useEffect(() => { const request = mode === "settings" ? api.get<{ settings: Record<string, string> }>("/settings").then((data) => setSettings({ ...defaults, ...data.settings })) : api.get<{ users: User[] }>("/users").then((data) => setUsers(data.users)); request.catch((e) => setError(e instanceof Error ? e.message : "Could not load data")).finally(() => setLoading(false)); }, [mode]);
  const saveSettings = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); setError(""); try { await api.put("/settings", settings); setSaved(true); setTimeout(() => setSaved(false), 2500); } catch (e) { setError(e instanceof Error ? e.message : "Could not save settings"); } finally { setSaving(false); } };
  const addUser = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); setError(""); try { await api.post("/users", form); setOpen(false); setForm({ name: "", email: "", password: "", role: "CASHIER" }); await load(); } catch (e) { setError(e instanceof Error ? e.message : "Could not create user"); } finally { setSaving(false); } };
  if (loading) return <Spinner label={`Loading ${mode}`} />;
  if (mode === "settings") return <div><PageTitle title="Settings" subtitle="Store identity, currency, tax and receipt preferences" />{error && <ErrorNotice message={error} />}<form onSubmit={saveSettings} className="grid gap-4 xl:grid-cols-[1fr_.7fr]"><Panel className="p-5"><div className="mb-5 flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-indigo-50 text-indigo-600"><ShieldCheck size={21} /></span><div><h2 className="font-bold">Store information</h2><p className="text-xs text-slate-500">Shown on receipts and reports</p></div></div><div className="space-y-4"><Field label="Shop name"><Input value={settings.shopName} onChange={(e) => setSettings({ ...settings, shopName: e.target.value })} required /></Field><Field label="Address"><Textarea value={settings.shopAddress} onChange={(e) => setSettings({ ...settings, shopAddress: e.target.value })} /></Field><Field label="Phone"><Input value={settings.shopPhone} onChange={(e) => setSettings({ ...settings, shopPhone: e.target.value })} /></Field><Field label="Receipt footer"><Textarea value={settings.receiptFooter} onChange={(e) => setSettings({ ...settings, receiptFooter: e.target.value })} /></Field></div></Panel><div className="space-y-4"><Panel className="p-5"><h2 className="font-bold">Checkout defaults</h2><div className="mt-4 space-y-4"><Field label="Currency symbol"><Input value={settings.currency} onChange={(e) => setSettings({ ...settings, currency: e.target.value })} maxLength={5} /></Field><Field label="Tax rate (%)"><Input type="number" min="0" max="100" step="0.01" value={settings.taxRate} onChange={(e) => setSettings({ ...settings, taxRate: e.target.value })} /></Field></div></Panel><Button type="submit" className="w-full" disabled={saving}><Save size={17} />{saving ? "Saving..." : saved ? "Saved" : "Save settings"}</Button></div></form></div>;
  return <div><PageTitle title="Users & roles" subtitle="Create accounts for admins, managers and cashiers" action={<Button onClick={() => setOpen(true)}><Plus size={17} />Add user</Button>} />{error && <ErrorNotice message={error} />}<Panel className="overflow-hidden">{users.length ? <div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="px-5 py-3.5">User</th><th className="px-4 py-3.5">Role</th><th className="px-4 py-3.5">Status</th><th className="px-4 py-3.5">Last login</th><th className="px-4 py-3.5">Created</th></tr></thead><tbody className="divide-y divide-slate-100">{users.map((user) => <tr key={user.id}><td className="px-5 py-3.5"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-indigo-50 text-xs font-bold text-indigo-600">{user.name.split(" ").map((p) => p[0]).join("").slice(0, 2)}</span><div><b>{user.name}</b><p className="text-xs text-slate-400">{user.email}</p></div></div></td><td className="px-4 py-3.5"><span className="rounded-full bg-indigo-50 px-2.5 py-1 text-xs font-semibold text-indigo-700">{user.role}</span></td><td className="px-4 py-3.5"><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-semibold text-emerald-700">{user.active ? "Active" : "Inactive"}</span></td><td className="px-4 py-3.5 text-xs text-slate-500">{user.lastLoginAt ? formatDate(user.lastLoginAt, true) : "Never"}</td><td className="px-4 py-3.5 text-xs text-slate-500">{user.createdAt ? formatDate(user.createdAt) : "—"}</td></tr>)}</tbody></table></div> : <Empty title="No users" text="Create an account to get started." />}</Panel><Modal open={open} onClose={() => setOpen(false)} title="Add user"><form onSubmit={addUser} className="space-y-4"><Field label="Full name"><Input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} required /></Field><Field label="Email"><Input type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} required /></Field><Field label="Temporary password" hint="At least 8 characters"><Input type="password" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} minLength={8} required /></Field><Field label="Role"><Select value={form.role} onChange={(e) => setForm({ ...form, role: e.target.value as Role })}><option value="CASHIER">Cashier</option><option value="MANAGER">Manager</option><option value="ADMIN">Admin</option></Select></Field><div className="rounded-xl bg-slate-50 p-3 text-xs leading-5 text-slate-600"><UserCog className="mb-2 text-indigo-600" size={18} /><b>Cashier:</b> POS and day-to-day records. <b>Manager:</b> stock, purchases and reports. <b>Admin:</b> full access including users.</div><Button type="submit" className="w-full" disabled={saving}>{saving ? "Creating..." : "Create user"}</Button></form></Modal></div>;
}
