"use client";

import { LoaderCircle, X } from "lucide-react";
import type { ButtonHTMLAttributes, InputHTMLAttributes, ReactNode, SelectHTMLAttributes, TextareaHTMLAttributes } from "react";

export function Button({ className = "", variant = "primary", ...props }: ButtonHTMLAttributes<HTMLButtonElement> & { variant?: "primary" | "secondary" | "danger" | "ghost" }) {
  const styles = { primary: "bg-indigo-600 text-white hover:bg-indigo-700 shadow-sm", secondary: "border border-slate-200 bg-white text-slate-700 hover:bg-slate-50", danger: "bg-rose-600 text-white hover:bg-rose-700", ghost: "text-slate-600 hover:bg-slate-100" };
  return <button {...props} className={`inline-flex min-h-10 items-center justify-center gap-2 rounded-xl px-4 text-sm font-semibold transition disabled:cursor-not-allowed disabled:opacity-50 ${styles[variant]} ${className}`} />;
}
export function Input(props: InputHTMLAttributes<HTMLInputElement>) { return <input {...props} className={`h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm text-slate-900 outline-none transition placeholder:text-slate-400 focus:border-indigo-500 focus:ring-3 focus:ring-indigo-100 ${props.className || ""}`} />; }
export function Select(props: SelectHTMLAttributes<HTMLSelectElement>) { return <select {...props} className={`h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm text-slate-900 outline-none focus:border-indigo-500 focus:ring-3 focus:ring-indigo-100 ${props.className || ""}`} />; }
export function Textarea(props: TextareaHTMLAttributes<HTMLTextAreaElement>) { return <textarea {...props} className={`min-h-24 w-full rounded-xl border border-slate-200 bg-white p-3 text-sm text-slate-900 outline-none focus:border-indigo-500 focus:ring-3 focus:ring-indigo-100 ${props.className || ""}`} />; }
export function Field({ label, children, hint }: { label: string; children: ReactNode; hint?: string }) { return <label className="block space-y-1.5"><span className="text-sm font-semibold text-slate-700">{label}</span>{children}{hint && <span className="block text-xs text-slate-500">{hint}</span>}</label>; }
export function Panel({ children, className = "" }: { children: ReactNode; className?: string }) { return <section className={`rounded-2xl border border-slate-200 bg-white shadow-[0_4px_16px_rgba(15,23,42,.04)] ${className}`}>{children}</section>; }
export function PageTitle({ title, subtitle, action }: { title: string; subtitle: string; action?: ReactNode }) { return <div className="mb-5 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-2xl font-bold tracking-tight text-slate-950">{title}</h1><p className="mt-1 text-sm text-slate-500">{subtitle}</p></div>{action}</div>; }
export function Spinner({ label = "Loading" }: { label?: string }) { return <div className="flex min-h-56 flex-col items-center justify-center gap-3 text-slate-500"><LoaderCircle className="animate-spin text-indigo-600" size={26} /><span className="text-sm">{label}...</span></div>; }
export function Empty({ title, text }: { title: string; text: string }) { return <div className="flex min-h-48 flex-col items-center justify-center px-6 text-center"><div className="mb-3 grid h-12 w-12 place-items-center rounded-2xl bg-slate-100 text-2xl">◎</div><p className="font-semibold text-slate-800">{title}</p><p className="mt-1 max-w-sm text-sm text-slate-500">{text}</p></div>; }
export function ErrorNotice({ message }: { message: string }) { return <div className="mb-4 rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700">{message}</div>; }
export function Modal({ title, open, onClose, children, wide = false }: { title: string; open: boolean; onClose: () => void; children: ReactNode; wide?: boolean }) { if (!open) return null; return <div className="fixed inset-0 z-[100] flex items-end justify-center bg-slate-950/45 p-0 backdrop-blur-sm sm:items-center sm:p-5" role="dialog" aria-modal="true"><button className="absolute inset-0" onClick={onClose} aria-label="Close dialog" /><div className={`relative max-h-[92vh] w-full overflow-y-auto rounded-t-3xl bg-white shadow-2xl sm:rounded-3xl ${wide ? "max-w-3xl" : "max-w-lg"}`}><div className="sticky top-0 z-10 flex items-center justify-between border-b border-slate-100 bg-white/95 px-5 py-4 backdrop-blur"><h2 className="text-lg font-bold text-slate-900">{title}</h2><button onClick={onClose} className="grid h-9 w-9 place-items-center rounded-xl text-slate-500 hover:bg-slate-100" aria-label="Close"><X size={19} /></button></div><div className="p-5">{children}</div></div></div>; }
export function StatusPill({ value }: { value: string }) { const good = ["COMPLETED", "ACTIVE", "SALE", "PURCHASE"].includes(value.toUpperCase()); return <span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-semibold ${good ? "bg-emerald-50 text-emerald-700" : value === "VOID" ? "bg-rose-50 text-rose-700" : "bg-amber-50 text-amber-700"}`}>{value.replaceAll("_", " ")}</span>; }
